------------------------------------------------
-- USERS TABLE
------------------------------------------------
CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name VARCHAR(100) NOT NULL,
                       role VARCHAR(100) NOT NULL,
                       created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                       updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

------------------------------------------------
-- CUSTOMER TABLE
------------------------------------------------
CREATE TABLE customer (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          account_number VARCHAR(250),
                          address VARCHAR(255) NOT NULL,
                          phone_number VARCHAR(20) NOT NULL,
                          CONSTRAINT fk_customer_user FOREIGN KEY (id)
                              REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);

------------------------------------------------
-- STAFF TABLE
------------------------------------------------
CREATE TABLE staff (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       username VARCHAR(100) NOT NULL UNIQUE,
                       password VARCHAR(100) NOT NULL,
                       is_active BOOLEAN NOT NULL,
                       CONSTRAINT fk_staff_user FOREIGN KEY (id)
                           REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);

------------------------------------------------
-- CATEGORY TABLE
------------------------------------------------
CREATE TABLE category (
                          id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          category_name VARCHAR(150) NOT NULL
);

------------------------------------------------
-- ITEM TABLE
------------------------------------------------
CREATE TABLE item (
                      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      item_name VARCHAR(255) NOT NULL,
                      description VARCHAR(500) DEFAULT '--- no description ---',
                      stock INT DEFAULT 0 NOT NULL,
                      category_id INT,
                      price INT NOT NULL,
                      created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                      updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                      brand VARCHAR(255) DEFAULT '--no brand--',
                      CONSTRAINT fk_item_category FOREIGN KEY (category_id)
                          REFERENCES category(id) ON DELETE SET NULL
);

------------------------------------------------
-- SALES HISTORY TABLE
------------------------------------------------
CREATE TABLE sales_history (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               customer_id BIGINT,
                               grand_total INT DEFAULT 0 NOT NULL,
                               created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                               CONSTRAINT fk_sales_customer FOREIGN KEY (customer_id)
                                   REFERENCES customer(id) ON DELETE SET NULL
);

------------------------------------------------
-- SALES ITEM TABLE
------------------------------------------------
CREATE TABLE sales_item (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            sales_history_id BIGINT NOT NULL,
                            item_id BIGINT,
                            unit INT DEFAULT 0 NOT NULL,
                            subtotal INT DEFAULT 0 NOT NULL,
                            sell_price INT,
                            CONSTRAINT fk_salesitem_history FOREIGN KEY (sales_history_id)
                                REFERENCES sales_history(id) ON DELETE CASCADE ON UPDATE CASCADE,
                            CONSTRAINT fk_salesitem_item FOREIGN KEY (item_id)
                                REFERENCES item(id) ON DELETE SET NULL
);
